name: Build and Release Resume

on:
  push:
    branches: [main]
    paths:
      - '**.tex'
      - '**.cls'
      - '**.sty'
      - '.docker/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/latex-builder
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build LaTeX document
        run: |
          mkdir -p output
          docker run --rm -v ${{ github.workspace }}:/latex \
            ghcr.io/${{ github.repository_owner }}/latex-builder:latest

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v$(date +'%Y.%m.%d')
          name: "Resume Update $(date +'%Y.%m.%d')"
          body: |
            📄 Resume update $(date +'%Y.%m.%d')

            **Commit**: ${{ github.sha }}
            **Branch**: main
          files: Anish_Shobith_P_S_Resume.pdf
