name: Build and Release Resume

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for relevant changes
        id: changes
        run: |
          CHANGED=0
          git fetch origin main
          if [[ $(git diff --name-only origin/main HEAD) =~ ^(\.docker\/|.*\.tex$|.*\.sty$|.*\.cls$) ]]; then
              CHANGED=1
          fi
          echo "changed=${CHANGED}" >> $GITHUB_OUTPUT

      - name: Set up Docker
        if: steps.changes.outputs.changed == '1'
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        if: steps.changes.outputs.changed == '1'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache Docker image
        if: steps.changes.outputs.changed == '1'
        uses: docker/build-push-action@v5
        with:
          context: .docker
          push: true
          tags: ghcr.io/${{ github.repository }}/latex-builder:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/latex-builder:(buildcache,latest)
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/latex-builder:buildcache,mode=max

      - name: Build LaTeX document
        if: steps.changes.outputs.changed == '1'
        run: |
          docker run --rm -v ${{ github.workspace }}:/latex \
            ghcr.io/${{ github.repository }}/latex-builder:latest \
            main.tex "Anish_Shobith_P_S_Resume.pdf"

      - name: Get current date
        id: date
        run: echo "date=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT

      - name: Get short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        if: steps.changes.outputs.changed == '1' && github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          tag_name: v${{ steps.date.outputs.date }}
          name: "Resume Update ${{ steps.date.outputs.date }}"
          body: |
            📄 Resume update for ${{ steps.date.outputs.date }}

            **Commit**: ${{ steps.sha.outputs.sha }}
            **Branch**: main

            [View PDF](https://github.com/${{ github.repository }}/releases/download/v${{ steps.date.outputs.date }}/Anish_Shobith_P_S_Resume.pdf)
          files: |
            Anish_Shobith_P_S_Resume.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
