name: Build and Release Resume

on:
  push:
    branches: [main]
    paths:
      - "**.tex"
      - "**.cls"
      - "**.sty"
      - ".docker/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository_owner }}/latex-builder
          tags: |
            type=raw,value=latest

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .docker
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build LaTeX document
        run: |
          mkdir -p output
          docker build -t pdflatex .docker
          docker run --rm -v "${{ github.workspace }}:/data" pdflatex -jobname="Anish_Shobith_P_S_Resume" main.tex

      - name: Metadata
        id: metadata
        run: |
          echo "date=$(date +'%d-%m-%Y')" >> $GITHUB_OUTPUT
          echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          tag_name: v${{ steps.metadata.outputs.date }}
          name: "Resume Update ${{ steps.metadata.outputs.date }}"
          body: |
            📄 Resume update for ${{ steps.metadata.outputs.date }}

            **Commit**: ${{ steps.metadata.outputs.sha }}
            **Branch**: main

            [View PDF](https://github.com/${{ github.repository }}/releases/download/v${{ steps.metadata.outputs.date }}/Anish_Shobith_P_S_Resume.pdf)
          files: |
            Anish_Shobith_P_S_Resume.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
