name: Build and Release Resume

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      actions: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and cache Docker image
        uses: docker/build-push-action@v5
        with:
          context: .docker
          push: true
          tags: ghcr.io/${{ github.repository }}/resume:latest
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/resume:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/resume:buildcache,mode=max

      - name: Build LaTeX document
        run: |
          docker run --rm -v ${{ github.workspace }}:/latex \
            ghcr.io/${{ github.repository }}/resume:latest \
            main.tex "Anish_Shobith_P_S_Resume.pdf"

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          draft: false
          prerelease: false
          tag_name: "release-${{ github.head_ref }}-${{ github.sha }}"
          name: "Release - ${{ github.head_ref }} (${{ github.sha }})"
          body: "Release for commit ${{ github.sha }} from branch ${{ github.head_ref }}"
          generate_release_notes: false
          files: |
            Anish_Shobith_P_S_Resume.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
