name: Build and Release Resume

on:
  push:
    branches: [main]
    paths:
      - "**.tex"
      - "**.cls"
      - "**.sty"
      - ".docker/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .docker
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ github.repository_owner }}/latex-builder:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build Resume
        run: |
          docker run --rm -v "${{ github.workspace }}:/data" \
            ghcr.io/${{ github.repository_owner }}/latex-builder \
            -jobname="Anish_Shobith_P_S_Resume" main.tex

      - name: Create Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: "Resume Update ${{ github.run_number }}"
          body: |
            ## 📄 Resume Update

            **Build**: #${{ github.run_number }}
            **Commit**: [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            **Author**: ${{ github.actor }}
            **Date**: ${{ github.event.head_commit.timestamp }}

            ### 📝 Changes
            ```
                ${{ github.event.head_commit.message }}
            ```

            ### 📎 Files
            - [Download Resume PDF](https://github.com/${{ github.repository }}/releases/download/v${{ github.run_number }}/Anish_Shobith_P_S_Resume.pdf)
          files: Anish_Shobith_P_S_Resume.pdf
          token: ${{ secrets.GITHUB_TOKEN }}
